name: Smiley
main: me.fromgate.smiley.Smiley
version: 0.2.0
author: fromgate, fromgate@gmail.com
commands:
   smile:
      aliases: [smiley]
      description: Smiley command
      usage: |
           /smile - displays current configurations
           /smile list [page] - displays available smileys
           /smile reload - reload configuration and smileys